Repository PLANALOG/PLANALOG-Frontend, pull requests merged in 2025-02, with the labels that each got.

#66 Feat: 마이페이지 API 연결 (#65)
  .idea/deploymentTargetSelector.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/planalog/network/user/FriendpageResponse.kt
  app/src/main/java/com/example/planalog/network/user/FriendpageService.kt
  app/src/main/java/com/example/planalog/network/user/MypageResponse.kt
  app/src/main/java/com/example/planalog/network/user/MypageService.kt
  app/src/main/java/com/example/planalog/network/user/ProfileimageService.kt
  app/src/main/java/com/example/planalog/ui/profile/EditcharacterActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/FriendpageFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/FriendpageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/profile/MypageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/profile/ProfileFragment.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
  app/src/main/res/layout/fragment_friendpage.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: ✨ Feature

#68 Fix: 회원정보수정 api 오류 수정 외 다른 api 연결 수정 및 정리(#67)
  app/src/main/java/com/example/planalog/network/user/FriendpageResponse.kt
  app/src/main/java/com/example/planalog/network/user/MypageService.kt
  app/src/main/java/com/example/planalog/network/user/ProfileimageService.kt
  app/src/main/java/com/example/planalog/network/user/UserService.kt
  app/src/main/java/com/example/planalog/network/user/request/UserUpdateRequest.kt
  app/src/main/java/com/example/planalog/network/user/response/MypageResponse.kt
  app/src/main/java/com/example/planalog/network/user/response/UserProfileImgResponse.kt
  app/src/main/java/com/example/planalog/network/user/response/UserResponse.kt
  app/src/main/java/com/example/planalog/network/user/response/UserUpdateResponse.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/EditcharacterActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/FriendpageFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/FriendpageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/profile/MypageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/profile/ProfileFragment.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
  app/src/main/java/com/example/planalog/ui/start/QnaActivity.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/java/com/example/planalog/ui/start/StartsetActivity.kt
Labels: 🐞 BugFix

#70 Feat: 플래너 조회 api 연결 완료
  app/src/main/java/com/example/planalog/network/planner/PlannerResponse.kt
  app/src/main/java/com/example/planalog/network/planner/PlannerService.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/java/com/example/planalog/utils/getCurrentDate.kt
Labels: ✨ Feature

#72 Feat: 할 일 생성 api 연결 (#71)
  app/src/main/java/com/example/planalog/network/planner/PlannerResponse.kt
  app/src/main/java/com/example/planalog/network/task/AddTaskRequest.kt
  app/src/main/java/com/example/planalog/network/task/AddTaskResponse.kt
  app/src/main/java/com/example/planalog/network/task/TaskService.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
Labels: ✨ Feature

#74 Feat: 로그아웃 api 연결 후 로그인 api 로직 수정(#73)
  app/src/main/java/com/example/planalog/network/NetworkModule.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/LoginService.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/LogoutResponse.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/TokenResponse.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
Labels: 🐞 BugFix, ✨ Feature, 📬 API

#75 Fix: 로그인 api 요청 파라미터 수정
  app/src/main/java/com/example/planalog/network/SocialLogin/LoginService.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
Labels: 🐞 BugFix, 📬 API

#76 Fix: 로그인 api 오류 수정
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
Labels: 🐞 BugFix, 📬 API

#79 Feat: 프로필 API 수정 및 추가 (#78)
  app/src/main/java/com/example/planalog/network/friend/FriendpageResponse.kt
  app/src/main/java/com/example/planalog/network/friend/FriendpageService.kt
  app/src/main/java/com/example/planalog/network/user/FriendCountResponse.kt
  app/src/main/java/com/example/planalog/network/user/FriendcountService.kt
  app/src/main/java/com/example/planalog/ui/profile/EditcharacterActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/FriendpageFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/ProfileFragment.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/res/layout/activity_editcharacter.xml
  app/src/main/res/layout/activity_editprofile.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#81 Fix: 로그인, 로그아웃 로직 수정 (#80)
  app/src/main/java/com/example/planalog/SplashActivity.kt
  app/src/main/java/com/example/planalog/network/NetworkModule.kt
  app/src/main/java/com/example/planalog/network/TokenRefreshCallback.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🐞 BugFix, 📬 API

#85 Feat: 게시물 생성 api 연결 (#64)
  app/src/main/java/com/example/planalog/network/post/PostApiService.kt
  app/src/main/java/com/example/planalog/network/post/PostRequest.kt
  app/src/main/java/com/example/planalog/network/post/PostResponse.kt
  app/src/main/java/com/example/planalog/network/post/RetrofitInstance.kt
  app/src/main/java/com/example/planalog/ui/post/PostFragment.kt
  app/src/main/java/com/example/planalog/ui/post/PostRepository.kt
  app/src/main/java/com/example/planalog/ui/post/PostResponse.kt
Labels: ✨ Feature, 📬 API

#86 Feat: 프로필 편집 수정 (#84)
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/ProfileFragment.kt
  app/src/main/res/drawable/fragment_profile.xml
  app/src/main/res/layout/activity_editcharacter.xml
  app/src/main/res/layout/activity_editprofile.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#88 Fix: 로그인, 로그아웃 로직 수정 (#87)
  app/src/main/java/com/example/planalog/SplashActivity.kt
  app/src/main/java/com/example/planalog/network/NetworkModule.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
  app/src/main/java/com/example/planalog/ui/start/StartActivity.kt
Labels: 🐞 BugFix

#93 Feat: 친구API 연결 (#92)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/planalog/MainActivity.kt
  app/src/main/java/com/example/planalog/network/friend/FriendApiService.kt
  app/src/main/java/com/example/planalog/network/friend/FriendDataService.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendListActivity.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendListAdapter.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendListFragment.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendListPagerAdapter.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageFragment.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/FriendpageFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/ProfileFragment.kt
  app/src/main/res/drawable/edittext_innershadow.png
  app/src/main/res/layout/activity_friendlist.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_friendlist.xml
  app/src/main/res/layout/item_friendlist.xml
  app/src/main/res/navigation/navigation_graph.xml
  gradle/libs.versions.toml
Labels: ✨ Feature, 📬 API

#95 Fix: 캘린더 오류 수정 (#94)
  app/src/main/java/com/example/planalog/network/user/UserService.kt
  app/src/main/java/com/example/planalog/network/user/response/FriendProfileResponse.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageFragment.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarDay.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarFragment.kt
  app/src/main/java/com/example/planalog/ui/home/memo/MemoAdapter.kt
  app/src/main/java/com/example/planalog/utils/generateCalendarDays.kt
Labels: 🐞 BugFix

#103 Feat: 팔로우 기능 추가 (#102)
  app/src/main/java/com/example/planalog/network/friend/AddFriendService.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageActivity.kt
  app/src/main/java/com/example/planalog/ui/home/api/SearchApiHelper.kt
  app/src/main/java/com/example/planalog/ui/post/PostDetailFragment.kt
  app/src/main/java/com/example/planalog/ui/post/PostFragment.kt
  app/src/main/java/com/example/planalog/ui/search/SearchAdapter.kt
  app/src/main/java/com/example/planalog/ui/search/SearchFragment.kt
  app/src/main/java/com/example/planalog/ui/search/SearchItem.kt
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/fragment_post_detail.xml
Labels: ✨ Feature, 📬 API

#105 Fix/#104 팔로우기능개선
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/java/com/example/planalog/MainActivity.kt
  app/src/main/java/com/example/planalog/network/api/FirendApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/PlannerApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/SearchApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/TaskApiHelper.kt
  app/src/main/java/com/example/planalog/network/friend/AddFriendService.kt
  app/src/main/java/com/example/planalog/network/friend/FriendRequestCallback.kt
  app/src/main/java/com/example/planalog/network/friend/FriendService.kt
  app/src/main/java/com/example/planalog/network/friend/FriendpageService.kt
  app/src/main/java/com/example/planalog/network/friend/request/FriendAddRequest.kt
  app/src/main/java/com/example/planalog/network/friend/response/FriendAddResponse.kt
  app/src/main/java/com/example/planalog/network/friend/response/FriendDeleteResponse.kt
  app/src/main/java/com/example/planalog/network/friend/response/FriendResponse.kt
  app/src/main/java/com/example/planalog/network/friend/response/FriendpageResponse.kt
  app/src/main/java/com/example/planalog/network/user/UserService.kt
  app/src/main/java/com/example/planalog/network/user/response/FriendProfileResponse.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendListAdapter.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendListFragment.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageActivity.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/search/SearchAdapter.kt
  app/src/main/java/com/example/planalog/ui/search/SearchFragment.kt
  app/src/main/res/drawable/follow_button_selector.xml
  app/src/main/res/layout/activity_friendpage.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/navigation_graph.xml
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: 🐞 BugFix, 📬 API

#110 Feat: 다른유저 불러오기 API연결 (#109)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/planalog/network/api/FirendApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/FriendCountHelper.kt
  app/src/main/java/com/example/planalog/network/friend/request/FriendRequest.kt
  app/src/main/java/com/example/planalog/network/user/FriendCountRequest.kt
  app/src/main/java/com/example/planalog/network/user/FriendcountService.kt
  app/src/main/java/com/example/planalog/network/user/UserService.kt
  app/src/main/java/com/example/planalog/network/user/response/FriendProfileResponse.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/WebviewActivity.kt
  app/src/main/res/layout/activity_editprofile.xml
  app/src/main/res/layout/activity_friendpage.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#112 Fix: 모먼트 api 연결 및 레이아웃 일부 수정 (#111)
  app/src/main/java/com/example/planalog/network/api/PlannerApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/PostApiHelper.kt
  app/src/main/java/com/example/planalog/network/planner/PlannerResponse.kt
  app/src/main/java/com/example/planalog/network/post/MomentRequest.kt
  app/src/main/java/com/example/planalog/network/post/MomentResponse.kt
  app/src/main/java/com/example/planalog/network/post/PostApiService.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/post/PostDetailFragment.kt
  app/src/main/java/com/example/planalog/ui/post/PostFragment.kt
  app/src/main/java/com/example/planalog/utils/getCurrentDate.kt
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/fragment_post_detail.xml
Labels: 🐞 BugFix, 🎨 Layout & Style, 📬 API

#114 Feat: 카테고리 생성 api 연결 및 리팩토링 (#113)
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/planalog/network/api/TaskCtgyApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/UserApiHelper.kt
  app/src/main/java/com/example/planalog/network/startset/IdcheckService.kt
  app/src/main/java/com/example/planalog/network/task_category/CtgyAddRequest.kt
  app/src/main/java/com/example/planalog/network/task_category/CtgyAddResponse.kt
  app/src/main/java/com/example/planalog/network/task_category/CtgyDeleteRequest.kt
  app/src/main/java/com/example/planalog/network/task_category/CtgyDeleteResponse.kt
  app/src/main/java/com/example/planalog/network/task_category/TaskCategoryService.kt
  app/src/main/java/com/example/planalog/network/user/UserService.kt
  app/src/main/java/com/example/planalog/network/user/request/UserUpdateRequest.kt
  app/src/main/java/com/example/planalog/network/user/response/NicknameCheckResponse.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/ProfileFragment.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/java/com/example/planalog/ui/start/StartActivity.kt
  app/src/main/java/com/example/planalog/ui/start/StartsetActivity.kt
  app/src/main/java/com/example/planalog/utils/PlannerStorageUtil.kt
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#121 Fix: 홈화면 플래너 타입별 오류 수정 (#120)
  app/src/main/java/com/example/planalog/MainActivity.kt
  app/src/main/java/com/example/planalog/network/api/TaskApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/TaskCtgyApiHelper.kt
  app/src/main/java/com/example/planalog/network/task/TaskService.kt
  app/src/main/java/com/example/planalog/network/task/request/DeleteTasksRequest.kt
  app/src/main/java/com/example/planalog/network/task/response/GetTasksResponse.kt
  app/src/main/java/com/example/planalog/network/task_category/TaskCategoryService.kt
  app/src/main/java/com/example/planalog/network/task_category/request/AddCtgyTaskRequest.kt
  app/src/main/java/com/example/planalog/network/task_category/request/CtgyAddRequest.kt
  app/src/main/java/com/example/planalog/network/task_category/request/CtgyDeleteRequest.kt
  app/src/main/java/com/example/planalog/network/task_category/response/AddCtgyTaskResponse.kt
  app/src/main/java/com/example/planalog/network/task_category/response/CtgyAddResponse.kt
  app/src/main/java/com/example/planalog/network/task_category/response/CtgyDeleteResponse.kt
  app/src/main/java/com/example/planalog/network/task_category/response/GetCtgyResponse.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/Category.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/CategoryAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/memo/MemoAdapter.kt
  app/src/main/java/com/example/planalog/utils/PlannerStorageUtil.kt
Labels: 🐞 BugFix

#123 Fix: 로그아웃 로직 수정 (#122)
  app/src/main/java/com/example/planalog/network/user/MypageService.kt
  app/src/main/java/com/example/planalog/network/user/response/MypageResponse.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/ProfileFragment.kt
Labels: 🐞 BugFix

#124 모멘트 수정
  app/src/main/java/com/example/planalog/network/api/CommentApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/PostApiHelper.kt
  app/src/main/java/com/example/planalog/network/post/MomentResponse.kt
  app/src/main/java/com/example/planalog/ui/post/PostFragment.kt
Labels: ✨ Feature, 📬 API

#126 삭제 버튼 변경
  app/src/main/res/layout/item_slide.xml
Labels: 🎨 Layout & Style

#127 Feat: 카카오 소셜 로그인 구현 (#125)
  .idea/deploymentTargetSelector.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/planalog/GlobalApplication.kt
  app/src/main/java/com/example/planalog/network/NetworkModule.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/LoginService.kt
  app/src/main/java/com/example/planalog/network/api/LoginApiHelper.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
  settings.gradle
Labels: ✨ Feature, 📬 API

#131 Feat: 메모형 플래너 캘린더 api 연결 (#130)
  app/src/main/java/com/example/planalog/network/api/PlannerApiHelper.kt
  app/src/main/java/com/example/planalog/network/api/TaskApiHelper.kt
  app/src/main/java/com/example/planalog/network/planner/PlannerCalendarResponse.kt
  app/src/main/java/com/example/planalog/network/planner/PlannerService.kt
  app/src/main/java/com/example/planalog/network/task/TaskService.kt
  app/src/main/java/com/example/planalog/network/task/request/TaskCompleteRequest.kt
  app/src/main/java/com/example/planalog/network/task/response/TaskCompleteResponse.kt
  app/src/main/java/com/example/planalog/ui/home/HomeBlogAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/HomeBlogItem.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarFragment.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/CategoryAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/memo/MemoAdapter.kt
  app/src/main/java/com/example/planalog/ui/start/StartActivity.kt
  app/src/main/java/com/example/planalog/utils/BlogDataUtil.kt
  app/src/main/res/drawable/img_friend_1.png
  app/src/main/res/drawable/img_friend_2.png
  app/src/main/res/drawable/img_friend_4.png
  app/src/main/res/drawable/img_friend_5.png
  app/src/main/res/drawable/img_friend_6.png
  app/src/main/res/drawable/img_friend_7.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_blog.xml
Labels: ✨ Feature, 📬 API

#133 삭제 버튼 수정
  app/src/main/java/com/example/planalog/ui/post/PostDetailFragment.kt
  app/src/main/java/com/example/planalog/ui/post/PostFragment.kt
  app/src/main/java/com/example/planalog/ui/post/SlidePagerAdapter.kt
  app/src/main/res/layout/item_slide.xml
Labels: 🐞 BugFix

#136 Feat: 마이페이지 모먼트 연결 (#135)
  app/src/main/java/com/example/planalog/network/api/PostApiHelper.kt
  app/src/main/java/com/example/planalog/network/post/PostApiService.kt
  app/src/main/java/com/example/planalog/network/user/MypageService.kt
  app/src/main/java/com/example/planalog/network/user/response/UserPageMomentResponse.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendListAdapter.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageActivity.kt
  app/src/main/java/com/example/planalog/ui/post/PostDetailFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/EditprofileActivity.kt
  app/src/main/java/com/example/planalog/ui/profile/MyPageMomentFragment.kt
  app/src/main/java/com/example/planalog/ui/profile/MypageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/profile/ProfileFragment.kt
  app/src/main/res/layout/activity_exitpopup.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_mypage_moment.xml
  app/src/main/res/navigation/navigation_graph.xml
Labels: ✨ Feature

#138 Feat: 친구페이지 모먼트 연결 (#137)
  app/src/main/java/com/example/planalog/network/api/FriendApiHelper.kt
  app/src/main/java/com/example/planalog/network/friend/FriendService.kt
  app/src/main/java/com/example/planalog/network/friend/response/FriendpageResponse.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageActivity.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/profile/MypageMomentAdapter.kt
  app/src/main/res/layout/activity_friendpage.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_userpage_moment.xml
Labels: 🐞 BugFix, ✨ Feature

#140 Feat: 페이지 모먼트 수정 (#139)
  app/src/main/java/com/example/planalog/network/api/FriendApiHelper.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageActivity.kt
  app/src/main/java/com/example/planalog/ui/friends/FriendpageMomentAdapter.kt
  app/src/main/java/com/example/planalog/ui/profile/MypageMomentAdapter.kt
  app/src/main/res/layout/item_mypage_moment.xml
  app/src/main/res/layout/item_userpage_moment.xml
Labels: 🐞 BugFix, ✨ Feature
