Repository PLANALOG/PLANALOG-Frontend, pull requests merged in 2025-01, with the labels that each got.

#9 Feature/#8 blogmoment
  app/src/main/res/drawable/ic_array.png
  app/src/main/res/drawable/ic_draft.png
  app/src/main/res/drawable/ic_photo.png
  app/src/main/res/drawable/ic_upload.png
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#11 Feat: 홈화면 UI 및 플래너 기능 구현(#7)
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/Category.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/CategoryAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/memo/ChecklistItem.kt
  app/src/main/java/com/example/planalog/ui/home/memo/MemoAdapter.kt
  app/src/main/java/com/example/planalog/utils/RandomColor.kt
  app/src/main/res/drawable/checkbox_selector.xml
  app/src/main/res/drawable/edge.xml
  app/src/main/res/drawable/edge_round_ctgy.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_reply.xml
  app/src/main/res/drawable/ic_tools.xml
  app/src/main/res/drawable/img_friend_ex.png
  app/src/main/res/drawable/img_home_blog_ex.png
  app/src/main/res/drawable/img_popup.png
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_light.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/home_planner_ctgy_item.xml
  app/src/main/res/layout/home_planner_memo_item.xml
  app/src/main/res/layout/home_planner_popup_menu.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#22 Feat: 캘린더 UI 구현 및 일부 기능 추가(#19)
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/planalog/MainActivity.kt
  app/src/main/java/com/example/planalog/SplashActivity.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarDay.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarFragment.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarItems.kt
  app/src/main/java/com/example/planalog/ui/home/calender/DropdownAdapter.kt
  app/src/main/java/com/example/planalog/utils/generateCalendarDays.kt
  app/src/main/java/com/example/planalog/utils/generateYearMonthOptions.kt
  app/src/main/java/com/example/planalog/utils/showDropdownMenu.kt
  app/src/main/res/drawable/circle_checked.xml
  app/src/main/res/drawable/circle_unchecked.xml
  app/src/main/res/drawable/dropdown_edge.xml
  app/src/main/res/drawable/ic_dropdown.png
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/ic_prev.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dropdown_recycler.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_calendar_day.xml
  app/src/main/res/layout/item_calendar_dropdown.xml
  app/src/main/res/layout/item_calendar_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ Feature

#25 Feat: 알림창 UI 구현(#23)
  app/src/main/java/com/example/planalog/MainActivity.kt
  app/src/main/java/com/example/planalog/ui/home/notify/NotifyFragment.kt
  app/src/main/res/drawable/ic_friend_2.png
  app/src/main/res/drawable/ic_friend_3.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_notify.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#27 Feat: 검색 UI 추가 (#26)
  app/src/main/res/drawable/edittext_edge.xml
  app/src/main/res/drawable/ic_edittext_search.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#29 Feat: 홈화면 플래너 자동 설정 기능 추가(#28)
  app/src/main/java/com/example/planalog/MainActivity.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
Labels: ✨ Feature

#31 Feature/#30 홈화면저장기능수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/Category.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/CategoryAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/memo/MemoAdapter.kt
  app/src/main/res/color/save_btn_color.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 BugFix, ✨ Feature

#39 Fix: 홈화면 카테고리형 플래너 기능 버그 수정 (#34)
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/Category.kt
  app/src/main/java/com/example/planalog/ui/home/ctgy/CategoryAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/memo/ChecklistItem.kt
  app/src/main/java/com/example/planalog/ui/home/memo/MemoAdapter.kt
  app/src/main/res/layout/home_planner_ctgy_item.xml
  app/src/main/res/layout/home_planner_memo_item.xml
Labels: 🐞 BugFix

#41 Feat: 검색화면 UI 수정 및 추가 (#40)
  app/src/main/java/com/example/planalog/ui/search/SearchFragment.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_word_delete.xml
  app/src/main/res/drawable/ic_search_word_history.xml
  app/src/main/res/drawable/img_friend_4.png
  app/src/main/res/drawable/img_friend_5.png
  app/src/main/res/drawable/img_friend_6.png
  app/src/main/res/drawable/img_friend_7.png
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/colors.xml
Labels: ✨ Feature

#42 Feat: 누락 부분 추가 커밋 (#40)
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#44 Feat: 알림창 동시응원 팝업 구현 (#43)
  app/src/main/java/com/example/planalog/ui/home/notify/ConfirmDialogFragment.kt
  app/src/main/java/com/example/planalog/ui/home/notify/NotifyFragment.kt
  app/src/main/res/layout/fragment_confirm_dialog.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature

#46 Feat: 로그인API 연결 중간점검 (#45)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/planalog/network/NetworkModule.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/KakaologinActivity.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/NaverloginActivity.kt
  app/src/main/java/com/example/planalog/network/startset/Idcheck.kt
  app/src/main/java/com/example/planalog/network/startset/NicknameCheckResponse.kt
  app/src/main/java/com/example/planalog/network/user/UserResponse.kt
  app/src/main/java/com/example/planalog/network/user/UserService.kt
  app/src/main/java/com/example/planalog/network/user/UserUpdateRequest.kt
  app/src/main/java/com/example/planalog/network/user/UserUpdateResponse.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
  app/src/main/java/com/example/planalog/ui/start/QnaActivity.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/java/com/example/planalog/ui/start/StartsetActivity.kt
  app/src/main/res/drawable/btn_round_error.xml
  app/src/main/res/layout/activity_web_view.xml
  app/src/main/res/xml/network_security_config.xml
Labels: ✨ Feature

#55 Feature/#49 캘린더기능추가
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarDay.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarFragment.kt
  app/src/main/java/com/example/planalog/ui/home/calender/SharedViewModel.kt
  app/src/main/java/com/example/planalog/ui/home/memo/ChecklistItem.kt
  app/src/main/java/com/example/planalog/ui/home/memo/MemoAdapter.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/java/com/example/planalog/utils/generateCalendarDays.kt
  app/src/main/java/com/example/planalog/utils/generateYearMonthOptions.kt
  app/src/main/java/com/example/planalog/utils/getCurrentDate.kt
  app/src/main/java/com/example/planalog/utils/savePlannerDate.kt
  app/src/main/java/com/example/planalog/utils/updateTaskCompletion.kt
Labels: 🐞 BugFix, ✨ Feature

#57 Feat: 네이버 로그인 로직 수정 (#56)
  .idea/deploymentTargetSelector.xml
  app/build.gradle
  app/src/main/java/com/example/planalog/MainActivity.kt
  app/src/main/java/com/example/planalog/network/NetworkModule.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/KakaologinActivity.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/NaverLoginService.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/NaverTokenResponse.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/NaverloginActivity.kt
  app/src/main/java/com/example/planalog/network/SocialLogin/TokenRefreshResponse.kt
  app/src/main/java/com/example/planalog/network/startset/IdcheckService.kt
  app/src/main/java/com/example/planalog/network/user/UserService.kt
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/java/com/example/planalog/ui/start/StartsetActivity.kt
  app/src/main/java/com/example/planalog/utils/isTokenExpired.kt
Labels: 🐞 BugFix, ✨ Feature

#59 Fix: 로그인 api 오류 원인 해결 (#58)
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
Labels: 🐞 BugFix

#60 Fix: 로그인 api 테스트용으로 변경해서 연결 (#58)
  app/build.gradle
  app/src/main/java/com/example/planalog/ui/home/HomeFragment.kt
  app/src/main/java/com/example/planalog/ui/home/calender/CalendarAdapter.kt
  app/src/main/java/com/example/planalog/ui/home/memo/MemoAdapter.kt
  app/src/main/java/com/example/planalog/ui/start/LoginActivity.kt
  app/src/main/java/com/example/planalog/ui/start/QnaActivity.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
  app/src/main/java/com/example/planalog/ui/start/StartsetActivity.kt
Labels: 🐞 BugFix

#61 Fix: 누락된 변경사항 커밋 (#58)
  app/src/main/java/com/example/planalog/MainActivity.kt
  app/src/main/java/com/example/planalog/ui/start/ResultActivity.kt
Labels: 🐞 BugFix

#63 Feat: 홈화면 UI 추가 수정 (#62)
  app/src/main/res/drawable/edge_home_profile_img.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature
